# Usamos una imagen oficial de PHP con Apache
FROM php:8.2-apache

# Instalamos las extensiones necesarias para conectar con MySQL
# (Por defecto PHP en Docker viene "pelón", hay que activarle cosas)
RUN docker-php-ext-install pdo pdo_mysql mysqli

# Activamos el módulo rewrite de Apache (buena práctica)
RUN a2enmod rewrite

# Copiamos todo tu código al servidor dentro del contenedor
COPY . /var/www/html/

# Damos permisos al usuario de Apache
RUN chown -R www-data:www-data /var/www/html